eureka:
  instance:
    hostname: localhost
  client:
    eureka-service-url:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8070
spring:
  application:
    name: schools
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/schools
      username: username
      password: password
    jpa:
      hibernate:
        ddl-auto: create
      database: postgresql
      dtabase-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092  # Adresse du serveur Kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: commande-service-group  # Groupe de consommateurs pour le service School
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
application:
  config:
    notification-url: http://localhost:8888/api/v1/notification