eureka:
  client:
    register-with-eureka: false
server:
  port:8222
spring:
  spring:
    application:
      name: gateway
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        routes:
          - id: students
            uri: http://localhost:8090
            predivates:
              - Path=/api/vi/notification/**
          - id: school
            uri: http://localhost:8070
            predivates:
              - Path=/api/vi/commande/**

